config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  root to: 'welcome#index'

  mount Sidekiq::Web => '/sidekiq'

  resources :articles do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :pictures do
      resources :comments, only: [:create, :edit, :update, :destroy]
    end
 
  end  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/weather' => 'weather#show'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy, as: :commentable
  has_many :pictures, dependent: :destroy


  
  before_validation :strip_html_tags, if: :text
  before_save :bold_markdown, if: :text

  validates :title, :text, presence: true
  validates :title, length: { minimum: 5, maximum: 40 }
  validates :title, uniqueness: true, if: :title_changed?
  validates :terms_of_service, acceptance: :true

  validate :custom_validation, if: :text

  def custom_validation
    if text.index(title)
          errors.add(:text, :cannot_contain_title)
    end
  end

  private

  def strip_html_tags
    text.gsub!(/<[^>]*>/, '')
  end
  
  def bold_markdown
    text.gsub!(/\*(.+?)\*/, '<b>\1</b>')
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]


  def new
    @article = Article.new
    render #opcjonalne, jeśli widok nie ma nazwy
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    authorize! :create, @article
    if @article.save
      flash[:success] = t('articles.create.success')
      redirect_to article_path(@article.id) #'/articles/#{articles}'
    else
      flash.now[:error] = t('article.create.error', problems: @article.errors.full_messages.to_sentence)
      render 'new'
    end
  end

  def index
    @authorize
    @articles = Article.all.accessible_by(current_ability, :index)
    render

  end

  def show

    @article = Article.find(params[:id])
    @comment = @article.comments.new
  end

  def edit 
    @article = Article.find(params[:id])
    authorize! :edit, @article

  end
  
  def update 
    @article = Article.find(params[:id])
    authorize! :update, @article
    if @article.update(article_params)
      redirect_to article_path(@article.id)
    else
      render 'edit' #TODO poinformować co się udało
    end
  end


  def destroy
    article = Article.find(params[:id])
    authorize! :destroy, article
    article.destroy
    redirect_to articles_path
  end


  private

  def article_params
    params.require(:article).permit(:title, :text, :terms_of_service)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= simple_form_for @article, url: url do |f|
  %p
    = f.input :title, input_html: {maxlenght: 40 }
    = f.input :text, placeholder: 'Lorem ipsum...'
    = f.input :terms_of_service, as: :boolean
    = f.button :submit

app/views/articles/edit.html.haml
%h1= @article.title
= render partial: 'form', locals: { url: article_path(@article.id) }
= link_to t('articles.show.index_link'), articles_path

app/views/articles/index.html.haml
%h1= t 'articles.index.title'
%table.table
  - @articles.each do |article|
    - if can?(:read, article)
      %tr
        %td= link_to article.title, article_path(article.id)
        %td= excerpt(article.text, '', radius: 100 )
        %td= article.created_at
        - if can?(:update, article)
          %td= link_to t('articles.index.edit_link'), edit_article_path(article.id)
        - if can?(:destroy, article)
          %td= link_to t('articles.index.delete_link'), article_path(article.id), method: :delete, data: { confirm: t('articles.index.delete_confirm')}
= link_to t('articles.index.new_link'), new_article_path

app/views/articles/new.html.haml
%h1= t 'articles.new.title'
= render partial: 'form', locals: { url: articles_path }
= link_to t('articles.new.index_link'), articles_path

app/views/articles/show.html.haml
%h1= @article.title
- if @article.user
  %h3
    = t('articles.show.author', defaut: 'Autor')
    \: #{@article.user.email}
= link_to t('articles.show.gallery', default: 'Galeria'), article_pictures_path(@article)
= link_to t('articles.show.new', default: 'Dodaj zdjęcia '), new_article_picture_path(@article)
%p
  = @article.text
= link_to t('articles.show.index_link'), articles_path
= simple_form_for @comment, url: article_comments_path(@article.id) do |f|
  = f.input :commenter
  = f.input :body
  = f.button :submit
- @article.comments.reject(&:new_record?).each do |comment|
  %div
    %strong>= comment.commenter
    \: #{comment.body}